[package]
name = "workspace-selector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "workspace-selector"
path = "main.rs"

[dependencies]
inquire = "0.6.2"
